travis:
  secure:
    BINSTAR_TOKEN: vigcTpRKPkjVuuh7H0f5oxdav7XY88aWFL24upqtB5s/qb8wPBzgStNI3LDTMdCSZA8QPKEHfhsrHARTqXmS2rNzQwgIfxEQD55dbKZ+M1vnDFfM4TFzn/zGHdPWXwbOi99cuWQDpLy5BVOCLPPMpxxyBZ93V4KSRaJp+TikGPCzvClXqSMpTZ3/Z7pG42kXFfrVEK+EAgy1ZgEEtQirnh+H6hOaNoujOQZe/W+WO36SnvSGRpuhRJU6TNOozmcr93n8Gvt+byVhOhnMcFipG8dQxeD0lXkn4Up9EwD0+ABE7/zymMaBUX8Z/gEh3VHwefJVF30Mo4SGvUGrqOOhlnaku5jyHb1RS9aCHsu9qBp0ifdFcGABcITH8HFGoxuTYPA5XJMjvusTExe828AESW2AXQvndIZKpHvNOSAX5S4lMuiJXTCRuu3Zvy56CgFZCmLEH6IJQ5RMunmhk6pduS5Qtg1pwQZaXRqg7T0hWisVa2L0NpdgAKShkMoXGoTeK10ujFuQkNdi8OGpBy5hnLKvFFd+Y64YvCEkj0BT3SvQLTjDLAdmTPt+lMrOTZi24lwYsa/jCDOthbd9da4JviRprOP4EDSmfG8P9ZB0UAw+GFSpUfXJJ/Nbuu3CTV+sazgnr0E7lMXoZizLwV4FqZkApg2OTBTNu+mrhahN2es=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
